name: Run searchVacantGym

on:
  schedule:
    - cron: '0 0-15,21-23 * * *'
  workflow_dispatch:

env:
  USER_ID: ${{ secrets.USER_ID }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: write
  pull-requests: write

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: playwright

      - name: Install playwright
        run: npx playwright install
        working-directory: playwright

      - name: Run searchVacantGym script
        run: npx ts-node src/searchVacantGym.ts
        working-directory: playwright

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update reservation status
          delete-branch: true
          title: けやきネット予約情報が更新されました
          reviewers: badmintoncryer
